# Generated by Django 5.0.3 on 2024-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Announcement", "0002_announcement_attachmentfile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="attachmentFile",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
