# Generated by Django 5.0.3 on 2024-03-14 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="student",
            managers=[],
        ),
    ]
