# Generated by Django 5.0.2 on 2024-03-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameofCompany', models.CharField(max_length=200)),
                ('profileOfCompany', models.TextField()),
                ('JobProfile', models.CharField(max_length=100)),
                ('JobDescription', models.TextField()),
                ('EmploymentType', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=200, null=True)),
                ('Linkedin', models.CharField(max_length=200, null=True)),
                ('Address', models.CharField(max_length=100)),
                ('Worklocation', models.CharField(max_length=100)),
                ('BranchChoice', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Engineering'), ('both', 'both')], max_length=50)),
                ('Eligibility', models.TextField()),
                ('stipend', models.CharField(max_length=200)),
                ('ctc', models.CharField(max_length=200)),
                ('Bond', models.CharField(max_length=100, null=True)),
                ('SelectionProcess', models.TextField()),
                ('start', models.DateField()),
                ('join_date', models.DateField()),
                ('end_of_registration', models.DateField()),
            ],
        ),
    ]
