# Generated by Django 5.0.2 on 2024-03-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_subject', models.CharField(max_length=200)),
                ('prerequisites', models.TextField()),
                ('training_organization', models.CharField(max_length=200)),
                ('join_date', models.DateField()),
                ('end_of_registration', models.DateField()),
            ],
        ),
    ]
